// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhRlMfJSN6fk82VYvr0H4pBBSaeJ35Z7Q',
    appId: '1:511173580988:web:52de75f612b6719b37d8b9',
    messagingSenderId: '511173580988',
    projectId: 'easacc-task-327f1',
    authDomain: 'easacc-task-327f1.firebaseapp.com',
    storageBucket: 'easacc-task-327f1.firebasestorage.app',
    measurementId: 'G-LDGF45PZPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfyLXnXMHlCwzeZfe3a1Aw8LPzHCZVGwg',
    appId: '1:511173580988:android:c8233f6aa36b3bfa37d8b9',
    messagingSenderId: '511173580988',
    projectId: 'easacc-task-327f1',
    storageBucket: 'easacc-task-327f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbcxamVwkPfTk9SLATLg62SlllYtcXIPQ',
    appId: '1:511173580988:ios:3c4f93aae6c06cbe37d8b9',
    messagingSenderId: '511173580988',
    projectId: 'easacc-task-327f1',
    storageBucket: 'easacc-task-327f1.firebasestorage.app',
    iosClientId: '511173580988-5l7etr0lefilgfa3v3c00587j8sv0eu0.apps.googleusercontent.com',
    iosBundleId: 'com.easacc.task.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbcxamVwkPfTk9SLATLg62SlllYtcXIPQ',
    appId: '1:511173580988:ios:d8ba3d041f05d8fd37d8b9',
    messagingSenderId: '511173580988',
    projectId: 'easacc-task-327f1',
    storageBucket: 'easacc-task-327f1.firebasestorage.app',
    iosClientId: '511173580988-0l0r9326v09akhcvmfvn3k9bob4i3om6.apps.googleusercontent.com',
    iosBundleId: 'com.example.easaccTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhRlMfJSN6fk82VYvr0H4pBBSaeJ35Z7Q',
    appId: '1:511173580988:web:dc2ed0237f0d414637d8b9',
    messagingSenderId: '511173580988',
    projectId: 'easacc-task-327f1',
    authDomain: 'easacc-task-327f1.firebaseapp.com',
    storageBucket: 'easacc-task-327f1.firebasestorage.app',
    measurementId: 'G-VKD2QKXFJ8',
  );
}
